import axios from "axios";

const provider = process.env.AI_PROVIDER || "openai";
const apiKey = process.env.AI_API_KEY || process.env.OPENAI_API_KEY;
const apiUrl = process.env.AI_API_URL || "https://api.openai.com/v1/chat/completions";
const model = process.env.AI_MODEL || "gpt-4o-mini";
const azureApiVersion = process.env.AZURE_OPENAI_API_VERSION || "2023-05-15";
const azureDeployment = process.env.AZURE_OPENAI_DEPLOYMENT_NAME || process.env.AI_MODEL;

const fallbackResponse = (title: string) =>
  `Sample ${title} generated by Ayonaire. Replace AI_API_KEY or OPENAI_API_KEY with a valid key to enable real AI output.`;

export const callAI = async (title: string, details: string): Promise<string> => {
  if (!apiKey) {
    return fallbackResponse(title);
  }

  const prompt = [
    {
      role: "system",
      content:
        "You are an expert career accelerator assistant. Help students prepare resumes, cover letters, job search strategies, portfolios, skill gap analysis, interview practice, and career roadmaps.",
    },
    {
      role: "user",
      content: details,
    },
  ];

  try {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };

    if (provider === "azure") {
      headers["api-key"] = apiKey;
    } else {
      headers.Authorization = `Bearer ${apiKey}`;
    }

    const requestData =
      provider === "azure"
        ? {
            model: azureDeployment,
            messages: prompt,
            max_tokens: 1200,
            temperature: 0.8,
            "api-version": azureApiVersion,
          }
        : {
            model,
            messages: prompt,
            max_tokens: 1200,
            temperature: 0.8,
          };

    const response = await axios.post(apiUrl, requestData, { headers });

    const text =
      response?.data?.choices?.[0]?.message?.content ||
      response?.data?.choices?.[0]?.text ||
      "";

    return text.trim() || fallbackResponse(title);
  } catch (error: unknown) {
    if (axios.isAxiosError(error)) {
      console.error("AI client error:", error.response?.data || error.message);
    } else if (error instanceof Error) {
      console.error("AI client error:", error.message);
    } else {
      console.error("AI client error:", error);
    }
    return fallbackResponse(title);
  }
};